# -*- coding: utf-8 -*-
"""Marketing_Data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q7P6hpVCrt-0CuLeSiSdiO5SZbU16c2k
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("Marketing_data.csv", sep=';')

df = df.dropna()
df = df.drop_duplicates()

df["Revenue"] = pd.to_numeric(df["Revenue"], errors="coerce")
df["Advertising_budget"] = pd.to_numeric(df["Advertising_budget"], errors="coerce")
df["Net_profit"] = pd.to_numeric(df["Net_profit"], errors="coerce")

# KPI Summary
print("Total Revenue:", df["Revenue"].sum())
print("Total Profit:", df["Net_profit"].sum())
print("Average ROI:", df["ROI"].mean())

# Revenue by Device
device_rev = df.groupby("User_device")["Revenue"].sum()

plt.figure(figsize=(8,5))
device_rev.plot(kind="bar")
plt.title("Revenue by User Device")
plt.show()

# ROI Distribution
plt.figure()
sns.histplot(df["ROI"], bins=20)
plt.title("ROI Distribution")
plt.show()

# Correlation Heatmap
plt.figure(figsize=(8,6))
sns.heatmap(df.corr(numeric_only=True), cmap="coolwarm")
plt.title("Correlation Matrix")
plt.show()

df.to_csv("Marketing_Cleaned_Data.csv", index=False)
files.download("Marketing_Cleaned_Data.csv")